name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request: {}

env:
  NODE_ENV: production

jobs:
  build-test:
    timeout-minutes: 20
    name: Build & Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip build')"
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with: {node-version: '10.x'}
      - name: Setup Volta
        uses: rwjblue/setup-volta@v1
      - name: Setup SHA
        uses: rlespinasse/github-slug-action@v2.x
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: development
      - name: Build Distribution
        run: yarn build
      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with: {name: out, path: out}
      - name: Run tests
        run: yarn test
